# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: sbezuhlyi
  tag: "v1.0.7-887a498"
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
