# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sbezuhlyi
  tag: "v1.0.5-d5c753b"

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"

