apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: kbot
    demo: kbot
spec:
  containers:
  - name: kbot
    image: gcr.io/my-kbot/kbot:latest
    ports:
    - containerPort: 8080
      name: http
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 3
      timeoutSeconds: 3
      periodSeconds: 3
      failureThreshold: 3