apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: kbot
    demo: kbot
spec:
  containers:
  - name: kbot
    image: gcr.io/my-kbot:latest
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 3