apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: kbot
    demo: kbot
spec:
  containers:
  - name: kbot
    image: gcr.io/my-kbot:latest
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "1024Mi"