apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "00 01 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k-bot
              image: k-bot
              command: ["version"]
          restartPolicy: OnFailure